export const createApptJson = {
  action: 'CRT',
  companyName: '',
  companyName2: '',
  arAccountNumber: '',
  firstName: 'Richard',
  lastName: 'Brown',
  middleInitial: '',
  suffix: '',
  emailAddress: 'Richardsbrown@gmail.com',
  address1: '1015 Prickly Pear Lane',
  address2: 'Apt 450',
  city: 'Phoenix',
  state: 'AZ',
  country: 'US',
  zipCode: '85250',
  customerType: 'Person',
  businessPrimaryPurchasingPhoneCollection: [
    {
      businessPhoneType: '',
      'businessPhoneNumber ': '',
      businessPhoneExtension: null,
    },
    {
      businessPhoneType: '',
      'businessPhoneNumber ': '',
      businessPhoneExtension: '',
    },
    {
      businessPhoneType: null,
      'businessPhoneNumber ': null,
      businessPhoneExtension: null,
    },
  ],
  phoneDetails: [
    {
      phoneType: 'Mobile',
      phoneNumber: '1234567890',
    },
    {
      phoneType: 'Home',
      phoneNumber: '1234567891',
    },
    {
      phoneType: 'Work',
      phoneNumber: '1234567898',
    },
  ],
  myAccount: true,
  aaaMembershipNumber: '55555',
  privateLabelCardholder: 'Yes',
  military: 'Yes',
  customerId: null,
  trimId: '555501',
  assemblyId: 'A',
  year: '2016',
  make: 'CHEVROLET',
  model: 'CORVETTE',
  fitmentLiftId: '',
  frontTireSize: '245/35 R19',
  rearTireSize: '285/30 R20',
  frontTireDiameter: '19',
  rearTireDiameter: '20',
  assemblyType: 'O.E.',
  color: 'Black',
  licensePlate: 'TYD8270',
  vehicleImage:
    'https://cdn.discounttire.com/sys-master/images/hec/h7c/8910181105694/201810100833_10722_21253.png_dt-vehicle-default-format_dt-vehicle-thumbNail',
  vehicleType: 'Fitment',
  genericVehicleCategory: null,
  genericVehicleSubCategory: null,
  customerVehicleId: null,
  orderType: 'BOPIS',
  orderDate: '2022-05-24',
  salesOrderId: '33301',
  siteId: '1284',
  articles: [
    {
      articleId: '000000000000084838',
      articleSize: '',
      articleType: '',
      quantity: '1',
      articleDescription: 'Free Flat Repair, Rotation, Inspection',
      tredWell: false,
    },
    {
      articleId: '000000000000084800',
      articleSize: null,
      articleType: '',
      quantity: '1',
      articleDescription: 'Free Rotation and Rebalance',
      tredWell: false,
    },
    {
      articleId: '000000000000080219',
      articleSize: '',
      articleType: null,
      quantity: '3',
      articleDescription: 'Installation and Life of Tire Maintenance',
      tredWell: false,
    },
    {
      articleId: '000000000000041848',
      articleSize: '265/70 R17 115T SL OWL',
      articleType: '',
      quantity: '3',
      articleDescription: 'Pathfinder HT',
      tredWell: true,
    },
    {
      articleId: '000000000000080017',
      articleSize: null,
      articleType: '',
      quantity: '3',
      articleDescription: 'Certs for Refund, Replacement',
      tredWell: false,
    },
    {
      articleId: '000000000000080075',
      articleSize: '',
      articleType: null,
      quantity: '3',
      articleDescription: 'State Required Environmental Fee',
      tredWell: false,
    },
    {
      articleId: '000000000000080224',
      articleSize: '',
      articleType: '',
      quantity: '4',
      articleDescription: 'Waste Tire Disposal Fee',
      tredWell: false,
    },
  ],
  unPaid: true,
  comments:
    'The ladder rack manufactured the 2x4 landscape dump The ladder rack manufactured the durable Express 2500 and once the wheel upfitted the tire.',
  workOrderId: null,
};

export const vtvData = {
  id: 'a2Z6u0000001pVbEAI',
  appointmentNumber: 'SA-125639',
  createdDate: '2023-06-06T11:12:25.000+0000',
  workTypeId: '08q590000000miMAAQ',
  schedStartTime: '2023-06-06T17:30:00.000+0000',
  schedEndTime: '2023-06-06T17:45:00.000+0000',
  activityType: 'Back Room',
  orderType: 'BOPIS',
  selectedServices: [],
  returnForService: null,
  comments: null,
  parentRecordId: '0WO6u00000035FXGAY',
  vehicle: '2019 TOYOTA 4RUNNER',
  hasArrived: false,
  isBOPIS: false,
  companyName: null,
  hasAppt: true,
  isRemoved: false,
  room: 'n/a',
  vehicleComments: null,
  waitingCounter: 2661,
  waitlistApptTime: '2023-06-06T17:30:00.000+0000',
  account: {
    firstName: 'Johnathan',
    lastName: 'D.Smyth Jr.',
    name: 'Johnathan D.Smyth Jr.',
    personMobilePhone: '1234567890',
    personHomePhone: '1234567891',
    personOtherPhone: null,
    phone: '1234567892',
    phoneWOM: null,
    businessName: null,
    customerType: 'PersonAccount',
  },
};
